name: sonarr_api
description: Dart abstraction for Sonarr's public API (https://sonarr.tv)
version: 0.0.1-pre.9
homepage: https://github.com/RoninComputer/package-sonarr-api
repository: https://github.com/RoninComputer/package-sonarr-api
issue_tracker: https://github.com/RoninComputer/package-sonarr-api/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

dev_dependencies:
  # Generators
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  # Tooling
  build_runner: ^2.3.3
  lints: ^2.0.1
